service_name = "demo2"
fifo_path = "/tmp/serviceUI/register_service.fifo"
serviceUIconnector_fifo_path = "/tmp/serviceUI/demo.fifo"

[[config]]
title = "Select config to change"
choices = [
    { label = "start_on_boot", description = "Start the service after boot", data = "True" },
    { label = "logs_path",  description = "Logs path", data = "/var/app/logs" },
    { label = "download_logs", description = "Download logs", data = "False" },
    { label = "Restart_at_midnight", description = "Auto restart the service at midnight", data = "True" }
]

[[menu]]
title = "Select Action"
choices = [
    { label = "Start", description = "Start the service" },
    { label = "Stop",  description = "Stop the service" },
    { label = "Status", description = "Show status" },
    { label = "Restart", description = "Restart the service" }
]

[[text_input]]
title = "Enter username"
prompt = "Username"
visible = true
default = "john.doe"

[[text_input]]
title = "Enter password"
prompt = "Mot de passe"
visible = false
default = ""

[[text_block]]
title = "Live Logs"
auto_refresh = true
content = "Booting..."
