[main]
type = "Form"
formid = "Main"
callback = "processMainForm"
title = "Main form"
subtitle = "this is the main form"
widgets = [{"Name" = "config", "Order"="Top", "Active"="True" }, 
           {"Name" = "login" , "Order"="Normal","Active"="True"},
           {"Name" = "back" , "Order"="Last","Active"="True"}, 
]

[config]
type = "Menu"
getData = "getConfig"
setData = ""
title = "Loaded config"
interactive = "False"
choices = [
    { label = "start_on_boot", description = "Start the service after boot", data = "True"},
    { label = "stop_on_boot", description = "Stop the service after boot", data = "False" },
    { label = "logs_path",  description = "Logs path", data = "/var/app/logs" },
    { label = "download_logs", description = "Download logs", data = "False"  },
    { label = "Restart_at_midnight", description = "Auto restart the service at midnight", data = "True"  },
  
]


[login]
type = "Text_Input"
getData="getLogin" 
setData="setLogin"
title = "Enter username"
prompt = "Username"
visible = true
default = "john.doe"
button = "Envoyer"

[back]
type = "Menu"     
getData = ""
setData = ""
title = ""
interactive = "True"
choices = [
    { label = "main.back", description = "Back", data = ""},
]

